### ISSUE TITLE
Trying to convert a json file (FF history) to html

### ISSUE THREAD

**Issue by sclaes** [Whoeza/json_and_html#1]
python ./json_and_html_core.py 
Running with default settings.
Traceback (most recent call last):
  File "./json_and_html_core.py", line 40, in <module>
    json_in_html_out()
  File "./json_and_html_core.py", line 25, in json_in_html_out
    html_table_from_json_dict: str = dict_and_html(
  File "/home/sclaes/.local/lib/python3.8/site-packages/dict_and_html/d_and_h.py", line 227, in dict_and_html
    'children': convert_dict_rows_into_table_rows(
  File "/home/sclaes/.local/lib/python3.8/site-packages/dict_and_html/modules/d_ht_convert_rows.py", line 67, in convert_dict_rows_into_table_rows
    for dict_key, dict_value in source_dictionary.items():
AttributeError: 'list' object has no attribute 'items'

Any idea why I get this error? Invalid input?

The json file is quite small
[{"id":"atkiMVfTnmNl","url":"https://addons.mozilla.org/en-GB/firefox/addon/sky-history-export/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search","title":"History Export – Get this Extension for 🦊 Firefox (en-GB)","lastVisitTime":1723639015380,"visitCount":1},{"id":"VxbbVQmt6XEE","url":"https://www.google.be/?gws_rd=ssl#q=avg","title":"avg - Google zoeken","lastVisitTime":1480332596983,"visitCount":1}]

**Comment by Whoeza** [comment]
Hi @sclaes! Welcome to my repo. :)
Glad I can be helpful.
The issue is very simple, lucky us: the program doesn't take JSON dictionaries nested inside lists (yet).

### Quick fix for your case:

So a quick fix is to create 2 .json files in the input/ directory, one for each of the two JSON dictionaries in your list.

```json
testing.json
{
  "id": "atkiMVfTnmNl",
  "url": "https://addons.mozilla.org/en-GB/firefox/addon/sky-history-export/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search",
  "title": "History Export – Get this Extension for 🦊 Firefox (en-GB)",
  "lastVisitTime": 1723639015380,
  "visitCount": 1
}
```
```json
testing2.json
{
  "id": "VxbbVQmt6XEE",
  "url": "https://www.google.be/?gws_rd=ssl#q=avg",
  "title": "avg - Google zoeken",
  "lastVisitTime": 1480332596983,
  "visitCount": 1
}
```

When run like this, it works and produces `testing.json.htm` and `testing2.json.htm` in the usual output directory.

This means: you could iterate your input files in a loop and call the script on each individual element inside the loop. The loop iterates the list and the result is individual calls with dictionaries.

### For me

Should I include a feature to allow converting JSON dictionaries nested in lists?
Would should the output be in that case?
While I'm thinking about it, I'll send you this reply and welcome your suggestions. :)
